// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Qaflaty.Infrastructure.Persistence;

#nullable disable

namespace Qaflaty.Infrastructure.Migrations
{
    [DbContext(typeof(QaflatyDbContext))]
    [Migration("20260212205152_AddStoreCustomersAndAddresses")]
    partial class AddStoreCustomersAndAddresses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Qaflaty.Domain.Catalog.Aggregates.Category.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_id");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Qaflaty.Domain.Catalog.Aggregates.FaqItem.FaqItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_published");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("StoreId", "SortOrder");

                    b.ToTable("faq_items", (string)null);
                });

            modelBuilder.Entity("Qaflaty.Domain.Catalog.Aggregates.PageConfiguration.PageConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("content_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<string>("PageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("page_type");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("StoreId", "Slug")
                        .IsUnique();

                    b.ToTable("page_configurations", (string)null);
                });

            modelBuilder.Entity("Qaflaty.Domain.Catalog.Aggregates.PageConfiguration.SectionConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("content_json");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<Guid>("PageConfigurationId")
                        .HasColumnType("uuid")
                        .HasColumnName("page_configuration_id");

                    b.Property<string>("SectionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("section_type");

                    b.Property<string>("SettingsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("settings_json");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("VariantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("variant_id");

                    b.HasKey("Id");

                    b.HasIndex("PageConfigurationId");

                    b.ToTable("section_configurations", (string)null);
                });

            modelBuilder.Entity("Qaflaty.Domain.Catalog.Aggregates.Product.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Qaflaty.Domain.Catalog.Aggregates.Store.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomDomain")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("custom_domain");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CustomDomain")
                        .IsUnique()
                        .HasFilter("custom_domain IS NOT NULL");

                    b.ToTable("stores", (string)null);
                });

            modelBuilder.Entity("Qaflaty.Domain.Catalog.Aggregates.StoreConfiguration.StoreConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FooterVariant")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("footer-standard")
                        .HasColumnName("footer_variant");

                    b.Property<string>("HeaderVariant")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("header-minimal")
                        .HasColumnName("header_variant");

                    b.Property<string>("ProductCardVariant")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("card-standard")
                        .HasColumnName("product_card_variant");

                    b.Property<string>("ProductGridVariant")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("grid-standard")
                        .HasColumnName("product_grid_variant");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("StoreId")
                        .IsUnique();

                    b.ToTable("store_configurations", (string)null);
                });

            modelBuilder.Entity("Qaflaty.Domain.Identity.Aggregates.Merchant.Merchant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_verified");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("merchants", (string)null);
                });

            modelBuilder.Entity("Qaflaty.Domain.Identity.Aggregates.Merchant.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("token");

                    b.HasKey("Id");

                    b.HasIndex("MerchantId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Qaflaty.Domain.Identity.Aggregates.StoreCustomer.CustomerRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("StoreCustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_customer_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("token");

                    b.HasKey("Id");

                    b.HasIndex("StoreCustomerId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("customer_refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Qaflaty.Domain.Identity.Aggregates.StoreCustomer.StoreCustomer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_verified");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("store_customers", (string)null);
                });

            modelBuilder.Entity("Qaflaty.Domain.Ordering.Aggregates.Customer.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_id");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("Qaflaty.Domain.Ordering.Aggregates.Order.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("StoreId");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("Qaflaty.Domain.Ordering.Aggregates.Order.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("product_name");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("Qaflaty.Domain.Ordering.Aggregates.Order.OrderStatusChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<string>("ChangedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("changed_by");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("from_status");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("to_status");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("order_status_changes", (string)null);
                });

            modelBuilder.Entity("Qaflaty.Domain.Catalog.Aggregates.Category.Category", b =>
                {
                    b.OwnsOne("Qaflaty.Domain.Catalog.ValueObjects.CategoryName", "Name", b1 =>
                        {
                            b1.Property<Guid>("CategoryId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("name");

                            b1.HasKey("CategoryId");

                            b1.ToTable("categories");

                            b1.WithOwner()
                                .HasForeignKey("CategoryId");
                        });

                    b.OwnsOne("Qaflaty.Domain.Catalog.ValueObjects.CategorySlug", "Slug", b1 =>
                        {
                            b1.Property<Guid>("CategoryId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("slug");

                            b1.HasKey("CategoryId");

                            b1.ToTable("categories");

                            b1.WithOwner()
                                .HasForeignKey("CategoryId");
                        });

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Slug")
                        .IsRequired();
                });

            modelBuilder.Entity("Qaflaty.Domain.Catalog.Aggregates.FaqItem.FaqItem", b =>
                {
                    b.OwnsOne("Qaflaty.Domain.Catalog.ValueObjects.BilingualText", "Answer", b1 =>
                        {
                            b1.Property<Guid>("FaqItemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Arabic")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("answer_ar");

                            b1.Property<string>("English")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("answer_en");

                            b1.HasKey("FaqItemId");

                            b1.ToTable("faq_items");

                            b1.WithOwner()
                                .HasForeignKey("FaqItemId");
                        });

                    b.OwnsOne("Qaflaty.Domain.Catalog.ValueObjects.BilingualText", "Question", b1 =>
                        {
                            b1.Property<Guid>("FaqItemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Arabic")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("question_ar");

                            b1.Property<string>("English")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("question_en");

                            b1.HasKey("FaqItemId");

                            b1.ToTable("faq_items");

                            b1.WithOwner()
                                .HasForeignKey("FaqItemId");
                        });

                    b.Navigation("Answer")
                        .IsRequired();

                    b.Navigation("Question")
                        .IsRequired();
                });

            modelBuilder.Entity("Qaflaty.Domain.Catalog.Aggregates.PageConfiguration.PageConfiguration", b =>
                {
                    b.OwnsOne("Qaflaty.Domain.Catalog.ValueObjects.BilingualText", "Title", b1 =>
                        {
                            b1.Property<Guid>("PageConfigurationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Arabic")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("title_ar");

                            b1.Property<string>("English")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("title_en");

                            b1.HasKey("PageConfigurationId");

                            b1.ToTable("page_configurations");

                            b1.WithOwner()
                                .HasForeignKey("PageConfigurationId");
                        });

                    b.OwnsOne("Qaflaty.Domain.Catalog.ValueObjects.PageSeoSettings", "SeoSettings", b1 =>
                        {
                            b1.Property<Guid>("PageConfigurationId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("NoFollow")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("seo_no_follow");

                            b1.Property<bool>("NoIndex")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("seo_no_index");

                            b1.Property<string>("OgImageUrl")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("seo_og_image_url");

                            b1.HasKey("PageConfigurationId");

                            b1.ToTable("page_configurations");

                            b1.WithOwner()
                                .HasForeignKey("PageConfigurationId");

                            b1.OwnsOne("Qaflaty.Domain.Catalog.ValueObjects.BilingualText", "MetaDescription", b2 =>
                                {
                                    b2.Property<Guid>("PageSeoSettingsPageConfigurationId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Arabic")
                                        .IsRequired()
                                        .HasMaxLength(500)
                                        .HasColumnType("character varying(500)")
                                        .HasColumnName("seo_description_ar");

                                    b2.Property<string>("English")
                                        .IsRequired()
                                        .HasMaxLength(500)
                                        .HasColumnType("character varying(500)")
                                        .HasColumnName("seo_description_en");

                                    b2.HasKey("PageSeoSettingsPageConfigurationId");

                                    b2.ToTable("page_configurations");

                                    b2.WithOwner()
                                        .HasForeignKey("PageSeoSettingsPageConfigurationId");
                                });

                            b1.OwnsOne("Qaflaty.Domain.Catalog.ValueObjects.BilingualText", "MetaTitle", b2 =>
                                {
                                    b2.Property<Guid>("PageSeoSettingsPageConfigurationId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Arabic")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("seo_title_ar");

                                    b2.Property<string>("English")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("seo_title_en");

                                    b2.HasKey("PageSeoSettingsPageConfigurationId");

                                    b2.ToTable("page_configurations");

                                    b2.WithOwner()
                                        .HasForeignKey("PageSeoSettingsPageConfigurationId");
                                });

                            b1.Navigation("MetaDescription")
                                .IsRequired();

                            b1.Navigation("MetaTitle")
                                .IsRequired();
                        });

                    b.Navigation("SeoSettings")
                        .IsRequired();

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("Qaflaty.Domain.Catalog.Aggregates.PageConfiguration.SectionConfiguration", b =>
                {
                    b.HasOne("Qaflaty.Domain.Catalog.Aggregates.PageConfiguration.PageConfiguration", null)
                        .WithMany("Sections")
                        .HasForeignKey("PageConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qaflaty.Domain.Catalog.Aggregates.Product.Product", b =>
                {
                    b.OwnsOne("Qaflaty.Domain.Catalog.ValueObjects.ProductInventory", "Inventory", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Quantity")
                                .HasColumnType("integer")
                                .HasColumnName("stock_quantity");

                            b1.Property<string>("Sku")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("sku");

                            b1.Property<bool>("TrackInventory")
                                .HasColumnType("boolean")
                                .HasColumnName("track_inventory");

                            b1.HasKey("ProductId");

                            b1.ToTable("products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsOne("Qaflaty.Domain.Catalog.ValueObjects.ProductName", "Name", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("name");

                            b1.HasKey("ProductId");

                            b1.ToTable("products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsOne("Qaflaty.Domain.Catalog.ValueObjects.ProductPricing", "Pricing", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.HasKey("ProductId");

                            b1.ToTable("products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");

                            b1.OwnsOne("Qaflaty.Domain.Common.ValueObjects.Money", "CompareAtPrice", b2 =>
                                {
                                    b2.Property<Guid>("ProductPricingProductId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("compare_at_price");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("compare_at_price_currency");

                                    b2.HasKey("ProductPricingProductId");

                                    b2.ToTable("products");

                                    b2.WithOwner()
                                        .HasForeignKey("ProductPricingProductId");
                                });

                            b1.OwnsOne("Qaflaty.Domain.Common.ValueObjects.Money", "Price", b2 =>
                                {
                                    b2.Property<Guid>("ProductPricingProductId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("price");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("price_currency");

                                    b2.HasKey("ProductPricingProductId");

                                    b2.ToTable("products");

                                    b2.WithOwner()
                                        .HasForeignKey("ProductPricingProductId");
                                });

                            b1.Navigation("CompareAtPrice");

                            b1.Navigation("Price")
                                .IsRequired();
                        });

                    b.OwnsOne("Qaflaty.Domain.Catalog.ValueObjects.ProductSlug", "Slug", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("slug");

                            b1.HasKey("ProductId");

                            b1.ToTable("products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.Navigation("Inventory")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Pricing")
                        .IsRequired();

                    b.Navigation("Slug")
                        .IsRequired();
                });

            modelBuilder.Entity("Qaflaty.Domain.Catalog.Aggregates.Store.Store", b =>
                {
                    b.OwnsOne("Qaflaty.Domain.Catalog.ValueObjects.DeliverySettings", "DeliverySettings", b1 =>
                        {
                            b1.Property<Guid>("StoreId")
                                .HasColumnType("uuid");

                            b1.HasKey("StoreId");

                            b1.ToTable("stores");

                            b1.WithOwner()
                                .HasForeignKey("StoreId");

                            b1.OwnsOne("Qaflaty.Domain.Common.ValueObjects.Money", "DeliveryFee", b2 =>
                                {
                                    b2.Property<Guid>("DeliverySettingsStoreId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("delivery_fee");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("delivery_fee_currency");

                                    b2.HasKey("DeliverySettingsStoreId");

                                    b2.ToTable("stores");

                                    b2.WithOwner()
                                        .HasForeignKey("DeliverySettingsStoreId");
                                });

                            b1.OwnsOne("Qaflaty.Domain.Common.ValueObjects.Money", "FreeDeliveryThreshold", b2 =>
                                {
                                    b2.Property<Guid>("DeliverySettingsStoreId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("free_delivery_threshold");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("free_delivery_threshold_currency");

                                    b2.HasKey("DeliverySettingsStoreId");

                                    b2.ToTable("stores");

                                    b2.WithOwner()
                                        .HasForeignKey("DeliverySettingsStoreId");
                                });

                            b1.Navigation("DeliveryFee")
                                .IsRequired();

                            b1.Navigation("FreeDeliveryThreshold");
                        });

                    b.OwnsOne("Qaflaty.Domain.Catalog.ValueObjects.StoreBranding", "Branding", b1 =>
                        {
                            b1.Property<Guid>("StoreId")
                                .HasColumnType("uuid");

                            b1.Property<string>("LogoUrl")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("logo_url");

                            b1.Property<string>("PrimaryColor")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)")
                                .HasDefaultValue("#3B82F6")
                                .HasColumnName("primary_color");

                            b1.HasKey("StoreId");

                            b1.ToTable("stores");

                            b1.WithOwner()
                                .HasForeignKey("StoreId");
                        });

                    b.OwnsOne("Qaflaty.Domain.Catalog.ValueObjects.StoreName", "Name", b1 =>
                        {
                            b1.Property<Guid>("StoreId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("name");

                            b1.HasKey("StoreId");

                            b1.ToTable("stores");

                            b1.WithOwner()
                                .HasForeignKey("StoreId");
                        });

                    b.OwnsOne("Qaflaty.Domain.Catalog.ValueObjects.StoreSlug", "Slug", b1 =>
                        {
                            b1.Property<Guid>("StoreId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("slug");

                            b1.HasKey("StoreId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("stores");

                            b1.WithOwner()
                                .HasForeignKey("StoreId");
                        });

                    b.Navigation("Branding")
                        .IsRequired();

                    b.Navigation("DeliverySettings")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Slug")
                        .IsRequired();
                });

            modelBuilder.Entity("Qaflaty.Domain.Catalog.Aggregates.StoreConfiguration.StoreConfiguration", b =>
                {
                    b.OwnsOne("Qaflaty.Domain.Catalog.ValueObjects.CommunicationSettings", "CommunicationSettings", b1 =>
                        {
                            b1.Property<Guid>("StoreConfigurationId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("AiChatbotEnabled")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("comm_ai_chatbot_enabled");

                            b1.Property<string>("AiChatbotName")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("comm_ai_chatbot_name");

                            b1.Property<bool>("LiveChatEnabled")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("comm_live_chat_enabled");

                            b1.Property<string>("WhatsAppDefaultMessage")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("comm_whatsapp_default_message");

                            b1.Property<bool>("WhatsAppEnabled")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("comm_whatsapp_enabled");

                            b1.Property<string>("WhatsAppNumber")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("comm_whatsapp_number");

                            b1.HasKey("StoreConfigurationId");

                            b1.ToTable("store_configurations");

                            b1.WithOwner()
                                .HasForeignKey("StoreConfigurationId");
                        });

                    b.OwnsOne("Qaflaty.Domain.Catalog.ValueObjects.CustomerAuthSettings", "CustomerAuthSettings", b1 =>
                        {
                            b1.Property<Guid>("StoreConfigurationId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("AllowGuestCheckout")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(true)
                                .HasColumnName("auth_allow_guest_checkout");

                            b1.Property<string>("Mode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("auth_mode");

                            b1.Property<bool>("RequireEmailVerification")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("auth_require_email_verification");

                            b1.HasKey("StoreConfigurationId");

                            b1.ToTable("store_configurations");

                            b1.WithOwner()
                                .HasForeignKey("StoreConfigurationId");
                        });

                    b.OwnsOne("Qaflaty.Domain.Catalog.ValueObjects.FeatureToggles", "FeatureToggles", b1 =>
                        {
                            b1.Property<Guid>("StoreConfigurationId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("Analytics")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("feat_analytics");

                            b1.Property<bool>("Newsletter")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("feat_newsletter");

                            b1.Property<bool>("ProductSearch")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(true)
                                .HasColumnName("feat_product_search");

                            b1.Property<bool>("PromoCodes")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("feat_promo_codes");

                            b1.Property<bool>("Reviews")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("feat_reviews");

                            b1.Property<bool>("SocialLinks")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("feat_social_links");

                            b1.Property<bool>("Wishlist")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("feat_wishlist");

                            b1.HasKey("StoreConfigurationId");

                            b1.ToTable("store_configurations");

                            b1.WithOwner()
                                .HasForeignKey("StoreConfigurationId");
                        });

                    b.OwnsOne("Qaflaty.Domain.Catalog.ValueObjects.LocalizationSettings", "LocalizationSettings", b1 =>
                        {
                            b1.Property<Guid>("StoreConfigurationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("DefaultDirection")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasDefaultValue("rtl")
                                .HasColumnName("loc_default_direction");

                            b1.Property<string>("DefaultLanguage")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(5)
                                .HasColumnType("character varying(5)")
                                .HasDefaultValue("ar")
                                .HasColumnName("loc_default_language");

                            b1.Property<bool>("EnableBilingual")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(true)
                                .HasColumnName("loc_enable_bilingual");

                            b1.HasKey("StoreConfigurationId");

                            b1.ToTable("store_configurations");

                            b1.WithOwner()
                                .HasForeignKey("StoreConfigurationId");
                        });

                    b.OwnsOne("Qaflaty.Domain.Catalog.ValueObjects.PageToggles", "PageToggles", b1 =>
                        {
                            b1.Property<Guid>("StoreConfigurationId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("AboutPage")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(true)
                                .HasColumnName("page_about");

                            b1.Property<bool>("CartPage")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(true)
                                .HasColumnName("page_cart");

                            b1.Property<bool>("ContactPage")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(true)
                                .HasColumnName("page_contact");

                            b1.Property<bool>("FaqPage")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("page_faq");

                            b1.Property<bool>("PrivacyPage")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("page_privacy");

                            b1.Property<bool>("ShippingReturnsPage")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("page_shipping_returns");

                            b1.Property<bool>("TermsPage")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("page_terms");

                            b1.HasKey("StoreConfigurationId");

                            b1.ToTable("store_configurations");

                            b1.WithOwner()
                                .HasForeignKey("StoreConfigurationId");
                        });

                    b.OwnsOne("Qaflaty.Domain.Catalog.ValueObjects.SocialLinks", "SocialLinks", b1 =>
                        {
                            b1.Property<Guid>("StoreConfigurationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Facebook")
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("social_facebook");

                            b1.Property<string>("Instagram")
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("social_instagram");

                            b1.Property<string>("Snapchat")
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("social_snapchat");

                            b1.Property<string>("TikTok")
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("social_tiktok");

                            b1.Property<string>("Twitter")
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("social_twitter");

                            b1.Property<string>("YouTube")
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("social_youtube");

                            b1.HasKey("StoreConfigurationId");

                            b1.ToTable("store_configurations");

                            b1.WithOwner()
                                .HasForeignKey("StoreConfigurationId");
                        });

                    b.Navigation("CommunicationSettings")
                        .IsRequired();

                    b.Navigation("CustomerAuthSettings")
                        .IsRequired();

                    b.Navigation("FeatureToggles")
                        .IsRequired();

                    b.Navigation("LocalizationSettings")
                        .IsRequired();

                    b.Navigation("PageToggles")
                        .IsRequired();

                    b.Navigation("SocialLinks")
                        .IsRequired();
                });

            modelBuilder.Entity("Qaflaty.Domain.Identity.Aggregates.Merchant.Merchant", b =>
                {
                    b.OwnsOne("Qaflaty.Domain.Common.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("MerchantId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("email");

                            b1.HasKey("MerchantId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("merchants");

                            b1.WithOwner()
                                .HasForeignKey("MerchantId");
                        });

                    b.OwnsOne("Qaflaty.Domain.Identity.ValueObjects.PersonName", "FullName", b1 =>
                        {
                            b1.Property<Guid>("MerchantId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("full_name");

                            b1.HasKey("MerchantId");

                            b1.ToTable("merchants");

                            b1.WithOwner()
                                .HasForeignKey("MerchantId");
                        });

                    b.OwnsOne("Qaflaty.Domain.Identity.ValueObjects.HashedPassword", "PasswordHash", b1 =>
                        {
                            b1.Property<Guid>("MerchantId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("password_hash");

                            b1.HasKey("MerchantId");

                            b1.ToTable("merchants");

                            b1.WithOwner()
                                .HasForeignKey("MerchantId");
                        });

                    b.OwnsOne("Qaflaty.Domain.Common.ValueObjects.PhoneNumber", "Phone", b1 =>
                        {
                            b1.Property<Guid>("MerchantId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("phone");

                            b1.HasKey("MerchantId");

                            b1.ToTable("merchants");

                            b1.WithOwner()
                                .HasForeignKey("MerchantId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("FullName")
                        .IsRequired();

                    b.Navigation("PasswordHash")
                        .IsRequired();

                    b.Navigation("Phone");
                });

            modelBuilder.Entity("Qaflaty.Domain.Identity.Aggregates.Merchant.RefreshToken", b =>
                {
                    b.HasOne("Qaflaty.Domain.Identity.Aggregates.Merchant.Merchant", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qaflaty.Domain.Identity.Aggregates.StoreCustomer.CustomerRefreshToken", b =>
                {
                    b.HasOne("Qaflaty.Domain.Identity.Aggregates.StoreCustomer.StoreCustomer", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("StoreCustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qaflaty.Domain.Identity.Aggregates.StoreCustomer.StoreCustomer", b =>
                {
                    b.OwnsOne("Qaflaty.Domain.Common.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("StoreCustomerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("email");

                            b1.HasKey("StoreCustomerId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("store_customers");

                            b1.WithOwner()
                                .HasForeignKey("StoreCustomerId");
                        });

                    b.OwnsOne("Qaflaty.Domain.Identity.ValueObjects.PersonName", "FullName", b1 =>
                        {
                            b1.Property<Guid>("StoreCustomerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("full_name");

                            b1.HasKey("StoreCustomerId");

                            b1.ToTable("store_customers");

                            b1.WithOwner()
                                .HasForeignKey("StoreCustomerId");
                        });

                    b.OwnsOne("Qaflaty.Domain.Identity.ValueObjects.HashedPassword", "PasswordHash", b1 =>
                        {
                            b1.Property<Guid>("StoreCustomerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("password_hash");

                            b1.HasKey("StoreCustomerId");

                            b1.ToTable("store_customers");

                            b1.WithOwner()
                                .HasForeignKey("StoreCustomerId");
                        });

                    b.OwnsOne("Qaflaty.Domain.Common.ValueObjects.PhoneNumber", "Phone", b1 =>
                        {
                            b1.Property<Guid>("StoreCustomerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("phone");

                            b1.HasKey("StoreCustomerId");

                            b1.ToTable("store_customers");

                            b1.WithOwner()
                                .HasForeignKey("StoreCustomerId");
                        });

                    b.OwnsMany("Qaflaty.Domain.Identity.ValueObjects.CustomerAddress", "Addresses", b1 =>
                        {
                            b1.Property<Guid>("StoreCustomerId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100);

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100);

                            b1.Property<bool>("IsDefault");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasMaxLength(50);

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20);

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(100);

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(255);

                            b1.HasKey("StoreCustomerId", "__synthesizedOrdinal");

                            b1.ToTable("store_customers");

                            b1
                                .ToJson("addresses")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("StoreCustomerId");
                        });

                    b.Navigation("Addresses");

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("FullName")
                        .IsRequired();

                    b.Navigation("PasswordHash")
                        .IsRequired();

                    b.Navigation("Phone");
                });

            modelBuilder.Entity("Qaflaty.Domain.Ordering.Aggregates.Customer.Customer", b =>
                {
                    b.OwnsOne("Qaflaty.Domain.Ordering.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AdditionalInfo")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("additional_info");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("country");

                            b1.Property<string>("District")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("district");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("postal_code");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("street");

                            b1.HasKey("CustomerId");

                            b1.ToTable("customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsOne("Qaflaty.Domain.Ordering.ValueObjects.CustomerContact", "Contact", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.HasKey("CustomerId");

                            b1.ToTable("customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");

                            b1.OwnsOne("Qaflaty.Domain.Common.ValueObjects.Email", "Email", b2 =>
                                {
                                    b2.Property<Guid>("CustomerContactCustomerId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(255)
                                        .HasColumnType("character varying(255)")
                                        .HasColumnName("email");

                                    b2.HasKey("CustomerContactCustomerId");

                                    b2.ToTable("customers");

                                    b2.WithOwner()
                                        .HasForeignKey("CustomerContactCustomerId");
                                });

                            b1.OwnsOne("Qaflaty.Domain.Identity.ValueObjects.PersonName", "FullName", b2 =>
                                {
                                    b2.Property<Guid>("CustomerContactCustomerId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("full_name");

                                    b2.HasKey("CustomerContactCustomerId");

                                    b2.ToTable("customers");

                                    b2.WithOwner()
                                        .HasForeignKey("CustomerContactCustomerId");
                                });

                            b1.OwnsOne("Qaflaty.Domain.Common.ValueObjects.PhoneNumber", "Phone", b2 =>
                                {
                                    b2.Property<Guid>("CustomerContactCustomerId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("character varying(20)")
                                        .HasColumnName("phone");

                                    b2.HasKey("CustomerContactCustomerId");

                                    b2.ToTable("customers");

                                    b2.WithOwner()
                                        .HasForeignKey("CustomerContactCustomerId");
                                });

                            b1.Navigation("Email");

                            b1.Navigation("FullName")
                                .IsRequired();

                            b1.Navigation("Phone")
                                .IsRequired();
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Contact")
                        .IsRequired();
                });

            modelBuilder.Entity("Qaflaty.Domain.Ordering.Aggregates.Order.Order", b =>
                {
                    b.OwnsOne("Qaflaty.Domain.Ordering.ValueObjects.DeliveryInfo", "Delivery", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Instructions")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("delivery_instructions");

                            b1.HasKey("OrderId");

                            b1.ToTable("orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");

                            b1.OwnsOne("Qaflaty.Domain.Ordering.ValueObjects.Address", "Address", b2 =>
                                {
                                    b2.Property<Guid>("DeliveryInfoOrderId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("AdditionalInfo")
                                        .HasMaxLength(500)
                                        .HasColumnType("character varying(500)")
                                        .HasColumnName("delivery_additional_info");

                                    b2.Property<string>("City")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("delivery_city");

                                    b2.Property<string>("Country")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("delivery_country");

                                    b2.Property<string>("District")
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("delivery_district");

                                    b2.Property<string>("PostalCode")
                                        .HasMaxLength(20)
                                        .HasColumnType("character varying(20)")
                                        .HasColumnName("delivery_postal_code");

                                    b2.Property<string>("Street")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("delivery_street");

                                    b2.HasKey("DeliveryInfoOrderId");

                                    b2.ToTable("orders");

                                    b2.WithOwner()
                                        .HasForeignKey("DeliveryInfoOrderId");
                                });

                            b1.Navigation("Address")
                                .IsRequired();
                        });

                    b.OwnsOne("Qaflaty.Domain.Ordering.ValueObjects.OrderNotes", "Notes", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CustomerNotes")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("customer_notes");

                            b1.Property<string>("MerchantNotes")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("merchant_notes");

                            b1.HasKey("OrderId");

                            b1.ToTable("orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.OwnsOne("Qaflaty.Domain.Ordering.ValueObjects.OrderNumber", "OrderNumber", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("order_number");

                            b1.HasKey("OrderId");

                            b1.HasIndex("Value");

                            b1.ToTable("orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.OwnsOne("Qaflaty.Domain.Ordering.ValueObjects.OrderPricing", "Pricing", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid");

                            b1.HasKey("OrderId");

                            b1.ToTable("orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");

                            b1.OwnsOne("Qaflaty.Domain.Common.ValueObjects.Money", "DeliveryFee", b2 =>
                                {
                                    b2.Property<Guid>("OrderPricingOrderId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("delivery_fee");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("delivery_fee_currency");

                                    b2.HasKey("OrderPricingOrderId");

                                    b2.ToTable("orders");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderPricingOrderId");
                                });

                            b1.OwnsOne("Qaflaty.Domain.Common.ValueObjects.Money", "Subtotal", b2 =>
                                {
                                    b2.Property<Guid>("OrderPricingOrderId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("subtotal");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("subtotal_currency");

                                    b2.HasKey("OrderPricingOrderId");

                                    b2.ToTable("orders");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderPricingOrderId");
                                });

                            b1.OwnsOne("Qaflaty.Domain.Common.ValueObjects.Money", "Total", b2 =>
                                {
                                    b2.Property<Guid>("OrderPricingOrderId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("total");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("total_currency");

                                    b2.HasKey("OrderPricingOrderId");

                                    b2.ToTable("orders");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderPricingOrderId");
                                });

                            b1.Navigation("DeliveryFee")
                                .IsRequired();

                            b1.Navigation("Subtotal")
                                .IsRequired();

                            b1.Navigation("Total")
                                .IsRequired();
                        });

                    b.OwnsOne("Qaflaty.Domain.Ordering.ValueObjects.PaymentInfo", "Payment", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FailureReason")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("payment_failure_reason");

                            b1.Property<string>("Method")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("payment_method");

                            b1.Property<DateTime?>("PaidAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("paid_at");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("payment_status");

                            b1.Property<string>("TransactionId")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("transaction_id");

                            b1.HasKey("OrderId");

                            b1.ToTable("orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.Navigation("Delivery")
                        .IsRequired();

                    b.Navigation("Notes")
                        .IsRequired();

                    b.Navigation("OrderNumber")
                        .IsRequired();

                    b.Navigation("Payment")
                        .IsRequired();

                    b.Navigation("Pricing")
                        .IsRequired();
                });

            modelBuilder.Entity("Qaflaty.Domain.Ordering.Aggregates.Order.OrderItem", b =>
                {
                    b.HasOne("Qaflaty.Domain.Ordering.Aggregates.Order.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Qaflaty.Domain.Common.ValueObjects.Money", "UnitPrice", b1 =>
                        {
                            b1.Property<Guid>("OrderItemId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("unit_price");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("unit_price_currency");

                            b1.HasKey("OrderItemId");

                            b1.ToTable("order_items");

                            b1.WithOwner()
                                .HasForeignKey("OrderItemId");
                        });

                    b.Navigation("UnitPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("Qaflaty.Domain.Ordering.Aggregates.Order.OrderStatusChange", b =>
                {
                    b.HasOne("Qaflaty.Domain.Ordering.Aggregates.Order.Order", null)
                        .WithMany("StatusHistory")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qaflaty.Domain.Catalog.Aggregates.PageConfiguration.PageConfiguration", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("Qaflaty.Domain.Identity.Aggregates.Merchant.Merchant", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Qaflaty.Domain.Identity.Aggregates.StoreCustomer.StoreCustomer", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Qaflaty.Domain.Ordering.Aggregates.Order.Order", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("StatusHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
